
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk-node

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: Install KGrid CLI
        command: |
          npm config set package-lock false
          npm install

    - run:
            name: KGrid CLI Tests
            command: npm test
            environment:
              HOME:  /home/circleci/repo

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Create Release
        command: |

          if [ $RELEASE ]; then
              TAG_NAME="v$RELEASE"
              git config --global user.email "$GIT_USER_EMAIL"
              git config --global user.name "$GIT_USER_NAME"
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
              echo "Update package version to $RELEASE"
              npm version $RELEASE
              git tag
              git push
              git push origin $TAG_NAME
              npm publish --dry-run --access public

             fi

    - run:
        name: Deploy VuePress GitHub Pages
        command: |
              npm run oclif-readme
              chmod 775 .circleci/vuepress_deploy.sh && .circleci/vuepress_deploy.sh


workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master
